<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>me.hsgamer</groupId>
        <artifactId>topper-template</artifactId>
        <version>4.20.0-SNAPSHOT</version>
    </parent>

    <artifactId>topper-template-top-player-number</artifactId>
    <name>Topper Template - Top Player Number</name>
    <description>A Topper template to handle player-number leaderboards</description>

    <dependencies>
        <dependency>
            <groupId>me.hsgamer</groupId>
            <artifactId>topper-data-simple</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>me.hsgamer</groupId>
            <artifactId>topper-agent-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>me.hsgamer</groupId>
            <artifactId>topper-agent-update</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>me.hsgamer</groupId>
            <artifactId>topper-agent-snapshot</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>me.hsgamer</groupId>
            <artifactId>topper-agent-storage</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>me.hsgamer</groupId>
            <artifactId>topper-query-display-number</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>me.hsgamer</groupId>
            <artifactId>topper-query-holder</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>me.hsgamer</groupId>
            <artifactId>topper-query-snapshot</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>me.hsgamer</groupId>
            <artifactId>topper-storage-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>me.hsgamer</groupId>
            <artifactId>topper-value-string</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>