<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>me.hsgamer</groupId>
        <artifactId>topper-storage</artifactId>
        <version>4.20.0</version>
    </parent>

    <artifactId>topper-storage-flat</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>core</module>
        <module>properties</module>
        <module>converter</module>
        <module>configfile</module>
    </modules>

    <name>Topper Storage Flat</name>

    <dependencies>
        <dependency>
            <groupId>me.hsgamer</groupId>
            <artifactId>topper-storage-core</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>